# Generated by Django 4.1.7 on 2023-06-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_noteshare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
        migrations.DeleteModel(
            name='NoteShare',
        ),
    ]
